---
# Create a Firefox profile

# XXX - Ought to be able to delete profiles, or rebuild them.
# Unfortunately,
# https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
# doesn't list a way to do this.
# - name: "Delete profile {{ profile }}"
#   command:
#     - "{{ firefox_cmd }}"
#     - "-headless"
#     - "-no-remote"
#     - "-DeleteProfile"
#     - "{{ profile }}"
#   register: profile_status
#   when:
#     - profile_state == "absent"
#
# The manual way to do this would be to tweak the profiles.ini file:
# delete (or comment out) the entire stanza with the profile, and
# recursively delete its directory.
#
# - If deleting the default profile, pick a different one to be the default.
#   - If there are no other profiles, throw an error.
#   - Set "Default=1" on some other profile. Maybe the first one that isn't
#     the current one.
#   - Set "Default=<new default profile id>" on [InstallNNN], if it exists.
#     - Also make this change in installs.ini: that's a backup of the
#       Install section:
#       https://support.mozilla.org/en-US/kb/understanding-depth-profile-installation
# - Get the profile directory.
# - Delete the stanza
# - If desired, delete the profile directory.

- name: "Create profile {{ profile }}"
  block:
    - name: "Tell Firefox to create profile {{ profile }}"
      command:
        argv:
          - "{{ firefox_cmd }}"
          - "-headless"
          - "-no-remote"
          - "-CreateProfile"
          - "{{ profile }}"
      when: profiles.profiles[profile] is not defined
      register: create_profile

# Install addons (and themes)
- name: "Profile {{ profile }}: Install addons"
  vars:
    profile_subdir: "{{ firefox_dir }}/{{ profiles.profiles[profile].path | default('abcd1234'+profile) }}"
  include_tasks: firefox-addon.yml
  with_items: "{{ addons }}"
  loop_control:
    loop_var: addon_slug

- name: "Profile {{ profile }}: Tweak preferences"
  vars:
    profile_subdir: "{{ firefox_dir }}/{{ profiles.profiles[profile].path | default('dummy') }}"
  lineinfile:
    path: "{{ profile_subdir }}/prefs.js"
    regexp: '^user_pref\(\"{{ item }}\",.*'
    line: 'user_pref("{{ item }}", {{ prefs[item] }});'
    create: yes
    owner: "{{ firefox_owner | default(ansible_user_id)}}"
    group: "{{ firefox_group | default(ansible_effective_group_id)}}"
    mode: '0644'
    # If the value is "null", then remove this line altogether.
    # Useful for cases like "network.proxy.type: 5": 5 is the default,
    # so Firefox removes the line entirely.
    state: "{{ 'absent' if prefs[item] == None else 'present' }}"
  with_items: "{{ prefs }}"
  when:
    - prefs is defined
    - prefs != ""

# Install security devices
- name: Install security devices
  include_tasks: security-device.yaml
  with_items: "{{ security_devices }}"
  loop_control:
    loop_var: security_device
  when:
    - security_devices is defined
    - security_devices != ""
    - security_devices | length > 0
